CREATE TABLE public.tenant_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE, key text NOT NULL, value jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id, key));
CREATE TABLE public.audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid REFERENCES public.tenants(id) ON DELETE CASCADE, actor_user_id uuid, entity_type text NOT NULL, entity_id uuid, action text NOT NULL, before jsonb, after jsonb, ip_address text, user_agent text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_logs_tenant_idx ON public.audit_logs(tenant_id, created_at DESC);
CREATE TABLE public.permissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), key text NOT NULL UNIQUE, description text, category text);
CREATE TABLE public.roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid REFERENCES public.tenants(id) ON DELETE CASCADE, name text NOT NULL, description text, is_system boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX roles_system_name_unique ON public.roles(name) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX roles_tenant_name_unique ON public.roles(tenant_id, name) WHERE tenant_id IS NOT NULL;
CREATE TABLE public.role_permissions (role_id uuid NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE, permission_id uuid NOT NULL REFERENCES public.permissions(id) ON DELETE CASCADE, PRIMARY KEY (role_id, permission_id));
CREATE TABLE public.tenant_users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE, user_id uuid NOT NULL, is_active boolean NOT NULL DEFAULT true, joined_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id, user_id));
CREATE INDEX tenant_users_user_idx ON public.tenant_users(user_id);
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, tenant_id uuid REFERENCES public.tenants(id) ON DELETE CASCADE, role_id uuid NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id, tenant_id, role_id));
CREATE INDEX user_roles_user_idx ON public.user_roles(user_id, tenant_id);
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;